#########################################################################
# Config Service                                                        #
# Configurazione per l'avvio del Config Service                         #
#########################################################################

services:
  config-service:
    image: ghcr.io/cnr-anac/config-service:latest
    container_name: config-service
    restart: unless-stopped
    links:
      - postgres:postgres
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8888:8888
    environment:
    - spring.docker.compose.enabled=false
    - spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:-5432}/${DB_NAME}
    - spring.datasource.username=${DB_USER}
    - spring.datasource.password=${DB_PASSWORD}
    # Per l'accesso alla configurazione Spring Cloud Config disponibile al path /config
    # si utilizza la Basic Auth, queste credenziali devono essere fornite ai client che utilizzano
    # il config-service
    - spring.security.user.name=${SECURITY_USER_NAME}
    - spring.security.user.password=${SECURITY_USER_PASSWORD}
    # Questi due parametri controllano l'IDP OAuth usato per l'autenticazione conJWT degli 
    # endopoint REST di aggiornamento della configurazione
    - spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}
    - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI}

  postgres:
    image: 'postgres:17'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - '5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/5432'
      interval: 5s
      timeout: 5s
      retries: 12
    restart: unless-stopped
