spring:
  security:
    user:
      name: config-service-user
      password: config-service-password
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dica33.ba.cnr.it/keycloak/realms/trasparenzai
          jwk-set-uri: https://dica33.ba.cnr.it/keycloak/realms/trasparenzai/protocol/openid-connect/certs