spring:
  application:
    name: config-service
  profiles:
    active: jdbc
  security:
    user:
      name: config-service-user
      password: config-service-password
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dica33.ba.cnr.it/keycloak/realms/trasparenzai
          jwk-set-uri: https://dica33.ba.cnr.it/keycloak/realms/trasparenzai/protocol/openid-connect/certs

  cloud:
    config:
      server:
        prefix: /config
        jdbc:
          sql: SELECT "KEY", "VALUE" from PROPERTIES where APPLICATION=? and PROFILE=? and (LABEL=? OR LABEL is null)
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
flyway:
  url: jdbc:postgres://localhost:5432/configs
  user: "cnr-anac"
  password: "secret"

server:
  port: 8888
autoconfigure:
  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

jmx:
  default_domain: cloud.config.server
management:
  endpoints:
    web:
      base-path: /admin

security:
  oauth2:
    enabled: true
    roles:
      POST: ADMIN,SUPERUSER
      PUT: ADMIN,SUPERUSER
      DELETE: ADMIN,SUPERUSER
