CREATE TABLE IF NOT EXISTS properties (
    id BIGSERIAL PRIMARY KEY,
    version INT,
    APPLICATION TEXT NOT NULL,
    PROFILE TEXT,
    LABEL TEXT DEFAULT 'master',
    "KEY" TEXT NOT NULL,
    "VALUE" TEXT);
